name: Pipeline

on: [push]

env:
  AWS_ACCESS_KEY_ID:     "AKIAQHFTVRX34PJ7KG42"
  AWS_SECRET_ACCESS_KEY: "L2pbHN1nO9LX7bjuYK/ByX0ZVPVs8LKmuSXlW4A"
  AWS_DEFAULT_REGION:    "us-east-2"

jobs:
   deploy-staging:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: ./.github/action-deploy
        with:
          args: "staging"
  deploy-production:
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: ./.github/action-deploy
        with:
          args: "production"
